{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-b64
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/b64_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/b64/b64_{{ version }}.tar.gz
  sha256: ca5a9aea35716781b3cb180f9dd089bfe783c1bde84b723684ee333763178f64
  patches:
    - 0001-Collect-built-targets.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('rust') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('b64')"           # [not win]
    - "\"%R%\" -e \"library('b64')\""  # [win]

about:
  home: https://extendr.github.io/b64/
  dev_url: https://github.com/extendr/b64
  license: MIT
  summary: Provides a fast, lightweight, and vectorized base 64 engine to encode and decode character and raw vectors as well as files stored on disk.  Common base 64 alphabets are supported out of the box including the standard, URL-safe, bcrypt, crypt, 'BinHex', and IMAP-modified UTF-7 alphabets. Custom engines can be
    created to support unique base 64 encoding and decoding needs.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: b64
# Title: Fast and Vectorized Base 64 Engine
# Version: 0.1.1
# Authors@R: c( person("Josiah", "Parry", , "josiah.parry@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-9910-865X")), person("Etienne", "Bacher", email = "etienne.bacher@protonmail.com", role = "ctb", comment = c(ORCID = "0000-0002-9271-5075")))
# Description: Provides a fast, lightweight, and vectorized base 64 engine to encode and decode character and raw vectors as well as files stored on disk.  Common base 64 alphabets are supported out of the box including the standard, URL-safe, bcrypt, crypt, 'BinHex', and IMAP-modified UTF-7 alphabets. Custom engines can be created to support unique base 64 encoding and decoding needs.
# License: MIT + file LICENSE
# Encoding: UTF-8
# Language: en
# RoxygenNote: 7.3.0
# Config/rextendr/version: 0.3.1.9000
# SystemRequirements: Cargo (Rust's package manager), rustc
# Suggests: blob, testthat (>= 3.0.0)
# Config/testthat/edition: 3
# URL: https://extendr.github.io/b64/, https://github.com/extendr/b64
# BugReports: https://github.com/extendr/b64/issues
# NeedsCompilation: yes
# Packaged: 2024-07-01 20:50:25 UTC; josiahparry
# Author: Josiah Parry [aut, cre] (<https://orcid.org/0000-0001-9910-865X>), Etienne Bacher [ctb] (<https://orcid.org/0000-0002-9271-5075>)
# Maintainer: Josiah Parry <josiah.parry@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-07-01 22:50:04 UTC
